export const FETCH_GITHUB_REPO_START = "FETCH_GITHUB_REPO_START";
export const FETCH_GITHUB_REPO_SUCCESS = "FETCH_GITHUB_REPO_SUCCESS";
export const FETCH_GITHUB_REPO_FAILED = "FETCH_GITHUB_REPO_FAILED";
export const REMOVE_USER = "REMOVE_USER";
export const ON_OPEN_MODAL = "ON_OPEN_MODAL";
export const ON_CLOSE_MODAL = "ON_CLOSE_MODAL";
