export const FETCH_GITHUB_REPO_START = "FETCH_GITHUB_REPO_START";
export const FETCH_GITHUB_REPO_SUCCESS = "FETCH_GITHUB_REPO_SUCCESS";
export const FETCH_GITHUB_REPO_FAILED = "FETCH_GITHUB_REPO_FAILED";
